### To DO:
# 2. Farbenskalen anpassen: colorramps? grDevices?
### Dann aber fertig!!!! du musst endlich schreiben!!!

### Network Traffic Analysis Visualization Script 3 ###

library(igraph)
library(ggplot2)  # For plotting
#install.packages("ggraph") # For network graph creation
library(ggraph)    # For network graph visualization
library(dplyr)    # For data manipulation
library(tidyverse)


# Enhanced Concentric Network Visualization Top10 Apps Black Backround --------------------

rm(df, user_node, top_apps, df_filtered, top_domains,
   edges_l1, edges_l2, edges_l3, all_edges, g,
   nodes_df, layout_df, layout_matrix)

# loading necessary libraries
library(tidyverse)
library(igraph)
library(ggraph)

# loading the dataset
df <- read_csv("Output/Tables/merged_data_all_more_info_df.csv")


# 1. Data Prep and Filtering ---------------------------------------------------------

# filtering out Non-Tracker Domains
df <- df %>%
  filter(TrackerBlackListXL == TRUE | domainType == 1) #%>%
  
# defining the user node name
user_node <- "User"

# aggregating hits to find the most active apps and domains
# filtering to top 10 apps and top 50 domains to prevent visual clutter ("hairball" graph)
top_apps <- df %>%
  group_by(AppName) %>%
  summarise(total_hits = sum(hits, na.rm = TRUE)) %>%
  slice_max(order_by = total_hits, n = 10) %>%
  pull(AppName)

df_filtered <- df %>%
  filter(AppName %in% top_apps)

top_domains <- df_filtered %>%
  group_by(domain) %>%
  summarise(total_hits = sum(hits, na.rm = TRUE)) %>%
  slice_max(order_by = total_hits, n = 50) %>%
  pull(domain)

df_filtered <- df_filtered %>%
  filter(domain %in% top_domains)


# 2. Edge List ---------------------------------------------------------

# creating edges for each layer: user -> app -> domain -> owner

# layer 1: User -> App
edges_l1 <- df_filtered %>%
  #distinct(AppName) %>%
  group_by(AppName) %>%
  summarise(weight = sum(hits), .groups = "drop") %>%
  mutate(from = user_node, to = AppName, layer_edge = 1) %>%
  select(from, to, layer_edge, weight)

# layer 2: App -> Domain
edges_l2 <- df_filtered %>%
  group_by(AppName, domain) %>%
  summarise(weight = sum(hits), .groups = "drop") %>%
  mutate(from = AppName, to = domain, layer_edge = 2) %>%
  select(from, to, layer_edge, weight)

# layer 3: Domain -> Owner
edges_l3 <- df_filtered %>%
  mutate(Owner = ifelse(is.na(DomainOwnerName) | DomainOwnerName == "", "Unknown", DomainOwnerName)) %>%
  group_by(domain, Owner) %>%
  summarise(weight = sum(hits), .groups = "drop") %>%
  mutate(from = domain, to = Owner, layer_edge = 3) %>%
  select(from, to, layer_edge, weight)

# combining all edges
all_edges <- bind_rows(edges_l1, edges_l2, edges_l3)


# 3. Creating the graph object and node attributes -----------------------------

# creating graph from edges
g <- graph_from_data_frame(all_edges, directed = TRUE)

# identifying node layers
# user = 0, app = 1, domain = 2, owner = 3
V(g)$layer <- case_when(
  V(g)$name == user_node ~ 0,
  V(g)$name %in% edges_l1$to ~ 1,
  V(g)$name %in% edges_l2$to ~ 2,
  V(g)$name %in% edges_l3$to ~ 3,
  TRUE ~ 3 # fallback for owners that might share names
)

# assigning node types for coloring
V(g)$type <- case_when(
  V(g)$layer == 0 ~ "User",
  V(g)$layer == 1 ~ "App",
  V(g)$layer == 2 ~ "Domain",
  V(g)$layer == 3 ~ "Owner"
)


# 4. Calculating manual concentric layout---------------------------------------

# extracting node data
nodes_df <- data.frame(name = V(g)$name, layer = V(g)$layer)

# defining radii for each layer
radii <- c(0, 1, 2, 3) # relative distance from center

# calculating x, y coordinates
layout_df <- nodes_df %>%
  group_by(layer) %>%
  mutate(
    n = n(),
    index = row_number(),
    # distributing nodes evenly around the circle
    angle = 2 * pi * (index - 1) / n,
    r = radii[layer + 1],
    x = r * cos(angle),
    y = r * sin(angle)
  ) %>%
  ungroup() %>%
  # ensure user is exactly at 0,0
  mutate(
    x = ifelse(layer == 0, 0, x),
    y = ifelse(layer == 0, 0, y)
  )

# creating the layout matrix for ggraph
layout_matrix <- as.matrix(layout_df %>% select(x, y))


# 5. Plotting ---------------------------------------------------------

ggraph(g, layout = layout_matrix) +
  # drawing edges with slight curve
  geom_edge_arc(aes(alpha = ..index..), strength = 0.1, color = "grey50", show.legend = FALSE) +
  
  # I am defining the range of thickness for the edges
  scale_edge_width_continuous(range = c(0.1, 1) ) + #, guide = "none") +
  
  # forcing the removal of the alpha/index legend generated by the edges
  scale_edge_alpha_continuous(guide = "none") +
  
  # drawing nodes
  geom_node_point(aes(color = as.factor(type), size = as.factor(layer)), show.legend = TRUE) +

  # defining colors for layers (User, App, Domain, Owner)
  #scale_color_manual(values = c("User" = "white", "App" = "#00d2ff", "Domain" = "#ff007f", "Owner" = "#ffcc00")) +
  #scale_color_manual(values = c("User" = "white", "App" = "#ff007f", "Domain" = "#00d2ff", "Owner" = "#ffcc00")) +
  scale_color_manual(values = c("User" = "#00d2ff", "App" = "#ff007f", "Domain" = "white", "Owner" = "#ffcc00")) +
  #scale_size_manual(values = c("0" = 10, "1" = 6, "2" = 3, "3" = 5), guide = "none") +
  scale_size_manual(values = c("0" = 12, "1" = 6, "2" = 2, "3" = 10), guide = "none") +
  
  # adding text labels
  geom_node_text(aes(label = name), repel = TRUE, 
                 #box.padding = 0.3,     # spacing between labels
                 #point.padding = -0.1, # no avoidance of nodes
                 color = "white", size = 3, bg.color = "black", bg.r = 0.15) +
  
  # styling the theme
  theme_void() +
  theme(
    plot.background = element_rect(fill = "#1a1a1a", color = NA),
    legend.position = "bottom",
    legend.text = element_text(color = "white"),
    legend.title = element_text(color = "white"),
    plot.title = element_text(color = "white", hjust = 0.5, size = 16)
  ) +
  labs(
    title = "Concentric Network Traffic: User > App > Domain > Owner",
    color = "Node Type"
  )


# Save Plot
ggsave("Output/Plots/concentric_network_traffic_Top10.png", width = 12, height = 8, dpi = 300)


# 6. Plotting with weights ---------------------------------------------------------

ggraph(g, layout = layout_matrix) +
  # drawing edges with slight curve
  geom_edge_arc(aes(edge_width = weight, alpha = ..index..), strength = 0.1, color = "grey50", show.legend = FALSE) +
  
  # I am defining the range of thickness for the edges
  scale_edge_width_continuous(range = c(0.2, 5), guide = "none") +
  
  # forcing the removal of the alpha/index legend generated by the edges
  scale_edge_alpha_continuous(guide = "none") +
  
  # drawing nodes
  geom_node_point(aes(color = as.factor(type), size = as.factor(layer)), show.legend = TRUE) +
  
  # defining colors for layers (User, App, Domain, Owner)
  #scale_color_manual(values = c("User" = "white", "App" = "#00d2ff", "Domain" = "#ff007f", "Owner" = "#ffcc00")) +
  #scale_color_manual(values = c("User" = "white", "App" = "#ff007f", "Domain" = "#00d2ff", "Owner" = "#ffcc00")) +
  scale_color_manual(values = c("User" = "#00d2ff", "App" = "#ff007f", "Domain" = "white", "Owner" = "#ffcc00")) +
  #scale_size_manual(values = c("0" = 10, "1" = 6, "2" = 3, "3" = 5), guide = "none") +
  scale_size_manual(values = c("0" = 12, "1" = 6, "2" = 2, "3" = 10), guide = "none") +
  
  # adding text labels
  geom_node_text(aes(label = name), repel = TRUE, 
                 #box.padding = 0.3,     # spacing between labels
                 #point.padding = -0.1, # no avoidance of nodes
                 color = "white", size = 3, bg.color = "black", bg.r = 0.15) +
  
  # styling the theme
  theme_void() +
  theme(
    plot.background = element_rect(fill = "#1a1a1a", color = NA),
    legend.position = "bottom",
    legend.text = element_text(color = "white"),
    legend.title = element_text(color = "white"),
    plot.title = element_text(color = "white", hjust = 0.5, size = 16)
  ) +
  labs(
    title = "Concentric Network Traffic: User > App > Domain > Owner",
    color = "Node Type"
  )


# Save Plot
ggsave("Output/Plots/concentric_network_traffic_Top10_edge_weights.png", width = 12, height = 8, dpi = 300)


# ### Fin du script ### ---------------------------------------------------
### Fin du script ###